version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: servify-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Mysql123@@
      MYSQL_DATABASE: servify
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: servify-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/servify
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mysql123@@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8084:8084"

  frontend:
    build: ./frontend
    container_name: servify-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  db_data:
